name: 'Trivy'

on:
  pull_request:
    branches:
      - main

jobs:
  trivy:
    name: 'Trivy'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v2

      - name: Run TF init
        run: terraform init -backend=false

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scanners: 'misconfig'
          scan-ref: .
          hide-progress: false
          ignore-unfixed: true
        env:
          TRIVY_TF_EXCLUDE_DOWNLOADED_MODULES: true
